### ISSUE TITLE
BiocManager should be on git.bioconductor.org

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocManager#10]
at packages/BiocManager ; maybe @nturaga can help?

**Comment by nturaga** [comment]
@mtmorgan @LiNk-NY , should it be under 

```
git@git.biocondcutor.org:packages/*
```

or

```
git@git.bioconductor.org:admin/*
```

**Comment by mtmorgan** [comment]
packages, I think

**Comment by LiNk-NY** [comment]
Just to update: It would be better to have `BiocManager` under `:admin/BiocManager` instead of `:packages` because it is not exactly a `Bioconductor` package.

**Comment by hpages** [comment]
A naive question: why dual host packages that are not part of the daily builds? Just curious...

**Comment by mtmorgan** [comment]
My feeling is that they 'belong' to us, not to github. For instance, the web site, bioconductor.org, and support site are also dual hosted (under `:admin/*`. This provides some consistency (for me, anyway) -- any time I'm dealing with something that is public bioconductor, I know to establish dual remotes and to push in both directions.

**Comment by hpages** [comment]
I can see that. But then another naive question is: why aren't projects like BBS, BBS-provision-cookbook, Contributions, packagebuilder, etc... not dual hosted? How do you draw the line?

**Comment by mtmorgan** [comment]
I don't know, really. I think BBS and packagebuilder should be dual-hosted. Contributions, despite it's current use, seems ephemeral -- we'll stop using it when the next way to contribute packages comes along -- and it's functionality (managing new packages submitted via github) isn't independent of github anyway. BBS-provision-cookbook still seems 'experimental' and not part of core Bioconductor functionality.

And it turns out that I was wrong about support.bioconductor.org -- it's not dual-hosted. I discovered this with

```
ssh git@git.bioconductor.org info|less
```

**Comment by hpages** [comment]
I feel that we should be more systematic or at least more transparent about what's dual hosted or not. Thanks for the reminder about `ssh git@git.bioconductor.org info|less`, that's helpful but still not as straightforward as I would have hoped. I've already been in the situation where I commit a change to the website on GitHub, hoping that the change will propagate in the next 20 min or so. But it didn't because the primary location for the website is on git.bioconductor.org and I had no idea about that. So I wonder how we could make the dual hosting status more visible.

**Comment by LiNk-NY** [comment]
Fun fact: `BiocManager` is triple hosted (`CRAN`, `GitHub`, `git.bioc`) :smiley:

**Comment by mtmorgan** [comment]
since the package is now on git.bioc, I'll close the issue.

**Comment by hpages** [comment]
If you include where the package tarballs are made available (in addition to git repos), Bioconductor packages are also triple hosted: GitHub, git.bioconductor.org, and bioconductor.org/packages/
