### ISSUE TITLE
Disable R version checking on systems without internet connectivity

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/BiocManager#102]
Our calculation cluster does not have internet connectivity and I'm thus installing and updating R packages from a intranet-local mirror of CRAN and BioC. Up to now this worked nicely, but now I get the following error from `BiocManager`:

```r
> BiocManager::install("Biobase")
Error: Bioconductor version '3.12' requires R version 'NA'; use
  `BiocManager::install(version = '3.12')` with R version 4.0; see
  https://bioconductor.org/install
```

I guess what happens is that the function tries to get the *correct* R version for BioC 3.12 from the internet. Maybe it would be possible to hard-code the R-to-BioC version within the package?

Note that I have already the options 

```r
$BIOCINSTALLER_ONLINE_DCF
[1] FALSE

$BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
[1] FALSE
```

my sessionInfo (I'm using the BioC docker in singularity):

```r
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocManager_1.30.12

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```

**Comment by mtmorgan** [comment]
This is a bit strange because BiocManager 1.30.12 was published on 2021-03-28 ; did you only recently update? Also, the current version (still working through CRAN) is 1.30.15; is this version still problematic?

**Comment by jorainer** [comment]
I tried to install the updated version manually with `R CMD INSTALL BiocManager_1.30.15.tar.gz` and this is the output I get:

```
During startup - Warning message:
Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
* installing to library ‘/usr/local/lib/R/host-site-library’
* installing *source* package ‘BiocManager’ ...
** package ‘BiocManager’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: `[<-.numeric_version`(`*tmp*`, , 2, value = NA_integer_)
  error: invalid 'value'
During startup - Warning messages:
1: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
2: package ‘BiocManager’ in options("defaultPackages") was not found 
** help
*** installing help indices
** building package indices
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: `[<-.numeric_version`(`*tmp*`, , 2, value = NA_integer_)
  error: invalid 'value'
During startup - Warning messages:
1: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
2: package ‘BiocManager’ in options("defaultPackages") was not found 
** installing vignettes
Warning in read.dcf(file.path(p, "DESCRIPTION"), c("Package", "Version")) :
  cannot open compressed file '/usr/local/lib/R/host-site-library/BiocManager/DESCRIPTION', probable reason 'No such file or directory'
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: `[<-.numeric_version`(`*tmp*`, , 2, value = NA_integer_)
  error: invalid 'value'
During startup - Warning messages:
1: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
2: package ‘BiocManager’ in options("defaultPackages") was not found 
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: `[<-.numeric_version`(`*tmp*`, , 2, value = NA_integer_)
  error: invalid 'value'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/host-site-library/BiocManager’
* restoring previous ‘/usr/local/lib/R/host-site-library/BiocManager’
```

I get the same error when using `install.packages("BiocManager")` (installing it from the local mirror) - `traceback()` just tells me `"No traceback available"`. Could be that I need to update the docker image on the cluster - I will try that and report back.

**Comment by LiNk-NY** [comment]
Hi Johannes, @jorainer 
The straightforward approach is to create a local copy of the config map and set the `"BIOCONDUCTOR_CONFIG_FILE"` environment variable / option to the path of the `config.yaml`. 
The offline map returns:
```
  Bioc   R BiocStatus RSPM MRAN
1 3.12 4.0       <NA> <NA> <NA>
```
and then uses the NA in `.version_validity` resulting in this error.

**Comment by jorainer** [comment]
Works, thanks @LiNk-NY !

**Comment by mtmorgan** [comment]
Oops, I was going to say that this should be documented, but I see that it is, in the vignette!

**Comment by LiNk-NY** [comment]
Though perhaps we can have a more informative message? @mtmorgan

**Comment by glin** [comment]
I was retesting https://github.com/Bioconductor/BiocManager/issues/93 with BiocManager 1.30.15, and ran into the same issue. Based on https://github.com/Bioconductor/BiocManager/issues/93, I thought setting `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS=FALSE` alone should still work, but I'd be fine if the new `BIOCONDUCTOR_CONFIG_FILE` setting replaces it going forward.

However, to ease migration for users in offline environments, it would still be nice to support using `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS=FALSE` alone if feasible. Based on @LiNk-NY's comment from https://github.com/Bioconductor/BiocManager/issues/93#issuecomment-812627116, `.version_validity` doesn't handle `NA`s in the `BiocStatus` column of the offline version map:
```r
> BiocManager:::.version_map_get_offline()
  Bioc   R BiocStatus RSPM MRAN
1 3.13 4.1       <NA> <NA> <NA>
```

https://github.com/Bioconductor/BiocManager/blob/3b33b8761428b037f61ad1d9025fe1cde8d945e1/R/version.R#L265

As a simple fix, could this ignore or handle `NA` values? One possibility might be:
```r
required <- map$R[map$Bioc == version & !map$BiocStatus %in% "future"]
```
