### ISSUE TITLE
Package not available warnings handled incorrectly

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocManager#112]
From https://github.com/Bioconductor/Contributions/issues/2180 and related to https://github.com/Bioconductor/BiocManager/issues/100, attempting to access a binary annotation repository during R CMD check generates an error like
```
Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.0 RC (2021-05-16 r80304)
Installing package(s) 'depmap'
Error in UseMethod("conditionMessage") : 
  no applicable method for 'conditionMessage' applied to an object of class "character"
Calls: [[ ... tryCatchList -> tryCatchOne -> doTryCatch -> download.file
Execution halted
```
This is because https://github.com/Bioconductor/BiocManager/commit/dd2b7fcc6fb94cc0c86c26cd6031ea846149f18e passes a character vector to .inet_warning when the `if` branch is taken https://github.com/Bioconductor/BiocManager/commit/dd2b7fcc6fb94cc0c86c26cd6031ea846149f18e#diff-e34c7a636f8638b3a90f0dc8b048f5b448d54d33ce3a452fc84940ba11e31e65R91-R97. But `.inet_warning()` is expecting a condition at https://github.com/Bioconductor/BiocManager/blob/064cbe1dddb0ccd6a0851ad192fcca40c5c2c870/R/inet.R#L9 in non-interactive sessions run under R CMD check.

The solution is along the lines of

```
diff --git a/R/inet.R b/R/inet.R
index 90e6233..4353afa 100644
--- a/R/inet.R
+++ b/R/inet.R
@@ -88,13 +88,15 @@ NULL
         })
     }, warning = function(w) {
         msg <- conditionMessage(w)
-        if (grepl("not available", msg))
+        if (grepl("not available", msg)) {
             msg <- gsub(
                 "this version of R",
                 paste0("Bioconductor version ", "'", version(), "'"),
                 msg
             )
-        .inet_warning(msg)
+            w <- simpleWarning(msg, conditionCall(w))
+        }
+        .inet_warning(w)
     })
 }
 ```

Obviously, this would benefit from a (difficult to write) unit test!

**Comment by LiNk-NY** [comment]
Thanks Martin, closed in https://github.com/Bioconductor/BiocManager/pull/115
