### ISSUE TITLE
 Installing BiocManager corrupt .rdb file 

### ISSUE THREAD

**Issue by zpavlovi2703** [Bioconductor/BiocManager#114]
I have been trying to install the BiocManager package to run DESeq2, however, I have been running into this error. 
The version number for R is 4.0.3. 

```
> library(BiocManager)
Error: package or namespace load failed for ‘BiocManager’ in get(method, envir = home):
 lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BiocManager/R/BiocManager.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1```

Trying to install DESeq2 gives the similar error:

```
> BiocManager::install("DESeq2")
Error in get(method, envir = home) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/BiocManager/R/BiocManager.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
4: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
5: In get(method, envir = home) :
  restarting interrupted promise evaluation
6: In get(method, envir = home) : internal error -3 in R_decompress1
```

Any advice on how to move forward? I have tried using alternate mirrors but the issue doesn't get resolved. I have also tried older versions, but the command defaults to the most recent version of BiocManager (1.30.16), which is the one that is giving me issues.

**Comment by vjcitn** [comment]
Please restart R.  That might be enough.  If not, then use `install.packages("BiocManager")` and select a suitable mirror.  If the problem persists, produce sessionInfo() after the error and post output here.

**Comment by zpavlovi2703** [comment]
Restarting R worked. Thank you!
