### ISSUE TITLE
BiocManager problems installing from local repository

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocManager#122]
From slack --

Here is the Rprofile.site:
```
if (file.exists('/private_stores/mirror/R/cran')) {
        suppressMessages(options("repos" = c(CRAN="file:///private_stores/mirror/R/cran")))
}
if (file.exists('/private_stores/mirror/R/bioconductor')) {
        suppressMessages(options(BIOCONDUCTOR_CONFIG_FILE="file:///private_stores/mirror/R/bioconductor/config.yaml"))
        suppressMessages(options(BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS=FALSE))
        suppressMessages(options(BioC_mirror = "file:///private_stores/mirror/R/bioconductor"))
}
```
Here's what the admin told me: "about to give up on bioconductor. i think there is abug in biocmanager. it won't let me use a local mirror. I kept on getting 'Error: Bioconductor version cannot be validated; no internet connection?' which is suppose to get disabled by setting BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS variable to false, but it isn't honoring it. After plenty of reinstalls, getting Error in `[<-.numeric_version`(`*tmp*`, , 2, value = NA_integer_) : when trying to do any BiocManager function. my guess it either doesn't support file:// anymore and it must be a http site or just some other bug. cran works fine."

**Comment by LiNk-NY** [comment]
Thanks Martin. 

Jenny, @jdrnevich, can you test the `NA_in_map` branch ? 
This should avoid the validation of the map given offline use. 

Best,
Marcel

**Comment by jdrnevich** [comment]
Thanks Martin and Marcel for responding so quickly. So `devtools::install_github("Bioconductor/BiocManager", ref = "NA_in_map")` ?

**Comment by LiNk-NY** [comment]
Yes, that should work. 
We will work on uploading the changes to CRAN in the meantime. 
Best,
Marcel

**Comment by jdrnevich** [comment]
The bug fix worked! Thanks so much again - my admin is super impressed at the speed and responsiveness of the Bioc team.
