### ISSUE TITLE
BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS not used

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#13]
Hi Martin, @mtmorgan 
It seems like this option is documented but not used in the package. 
Where should this option be enabled? 
Thanks!

**Comment by mtmorgan** [comment]
I'd suggest actually removing the documentation... Alternatively it could be consulted at the top of `.version_validity`, using something like what AnnnotationHub/R/zzz.R does and returning a message  coded like `.VERSION_MAP_UNABLE_TO_VALIDATE`

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan, how does this look https://github.com/Bioconductor/BiocManager/commit/e2053b105e9145cc569abb47a6c65b1cfb920eea?

**Comment by mtmorgan** [comment]
I made these commits; it seems to require quite convoluted logic and I'm not sure that it's entirely correct or complete, and I wonder whether it's worth it to support this feature? I think it comes from BiocInstaller and a desire to avoid the cost of looking up the version on-line each time, but we don't pay that cost now (just a one-time cost of getting the version map at start-up, and that fails quickly enough in an interactive session not to notice it).

245cc9e .version_validity_online_check() returns logical
6a2f71c valid() gains site_repository argument
46103be install() uses .repositories()
56620f7 clean up BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS message
8d70435 use BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
752ae5c improve BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS tests

245cc9e creates a stand-alone function to make testing and re-use easier; it returns a logical value

6a2f71c, 46103be maybe this should be separate, but in refactoring to avoid multiple warnings during `valid()` and `install()`, it seems like `valid()` needs to be (or at least should be) able to  handle `site_repository` as install() does.

8d70435 This actually uses the fact that the variable is set to TRUE to avoid trying to validate, etc!

**Comment by LiNk-NY** [comment]
Hi Martin @mtmorgan 
The proliferation of these checks have made load up really noisy. 

With the option set to FALSE in the `~/.Rprofile`: 
```
options(BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS = FALSE)
```

```r
> library(BiocManager)
Bioconductor version 3.7 (BiocManager 1.30.2), ?BiocManager::install for help
Bioconductor version cannot be validated; no internet connection?
Error: package or namespace load failed for 'BiocManager':
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: NULL
  error: invalid version specification 'Bioconductor version cannot be validated; no internet connection?'
In addition: Warning messages:
1: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
2: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS 
3: Bioconductor online version validation disabled; see
  ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
```

**Comment by LiNk-NY** [comment]
merged
