### ISSUE TITLE
test load fails on clean install of BiocManager

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#131]
This is on 4.2.0 (alpha) with a clean installation (no packages except recommended and `remotes`).

```r
> install.packages("BiocManager")
Installing package into '/media/bioc-devel'
(as 'lib' is unspecified)
trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/BiocManager_1.30.17.tar.gz'
Content type 'binary/octet-stream' length 288342 bytes (281 KB)
==================================================
downloaded 281 KB

* installing *source* package 'BiocManager' ...
** package 'BiocManager' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'BiocManager':
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: if (is.na(version)) version <- .VERSION_UNKNOWN
  error: argument is of length zero
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/media/bioc-devel/BiocManager'

The downloaded source packages are in
	'/tmp/RtmpXnysk2/downloaded_packages'
Warning message:
In install.packages("BiocManager") :
  installation of package 'BiocManager' had non-zero exit status
```

Conversely, it works with `--no-test-load`. 
Any ideas Martin @mtmorgan ?

**Comment by TJrogers86** [comment]
I am having this exact same issue

**Comment by nmclark2** [comment]
I am having the same issue on a local machine and on RSC running 3.6.2. Apps on RCS requiring BiocManager currently do not work as you get the same error when attempting to load the package:
`Bioconductor version 3.10 (BiocManager 1.30.17), R 3.6.3 (2020-02-29)
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: if (is.na(version)) version <- .VERSION_UNKNOWN
  error: argument is of length zero`

**Comment by LiNk-NY** [comment]
Hi all, 

This is an intermittent issue as we update the configuration map of the versions. 
We will have another update soon. 
Thank you for your patience. 

Best regards,
Marcel

**Comment by rmflight** [comment]
Just FYI, I'm seeing this same issue every time I try to load `BiocManager`. I thought it was tied to a new version, but apparently it affects my old one and I can't install any new Bioconductor :package: .

```
Bioconductor version 3.14 (BiocManager
  1.30.16), R 4.1.0 (2021-05-18)
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: if (is.na(version)) version <- .VERSION_UNKNOWN
  error: argument is of length zero
```

**Comment by LiNk-NY** [comment]
We've updated the configuration map in preparation for the Bioconductor release 3.15. 
You should **not** be seeing any more issues:

```r
> library(BiocManager)
Bioconductor version 3.15 (BiocManager 1.30.17), R 4.2.0 alpha (2022-04-05
  r82094)
```

Please restart your R session and let us know if they persist. 

Best,
Marcel

**Comment by rmflight** [comment]
All good on my end. Just get warning about being out of date now.

**Comment by hpages** [comment]
Note that `if (is.na(version)) version <- .VERSION_UNKNOWN` is failing to do what it's meant to do which is to catch the situation where the BioC version could not be obtained. Maybe it should do something like

```
if (length(version) != 1 || is.na(version))
    version <- .VERSION_UNKNOWN
```
so it never fails?

My 2 cents.

H.
