### ISSUE TITLE
Error: package or namespace load failed for ‘BiocManager’:  .onAttach failed in attachNamespace() for 'BiocManager', details:   call: if (max(r) == package_version("3.6")) {   error: argument is of length zero

### ISSUE THREAD

**Issue by Seraph-009** [Bioconductor/BiocManager#132]
Hello, recently，I met a problem that can not be solved by myself.
```
library(BiocManager) # I load the package on the linux 
Error: package or namespace load failed for ‘BiocManager’:
 .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: if (max(r) == package_version("3.6")) {
  error: argument is of length zero
In addition: Warning messages:
1: package ‘BiocManager’ was built under R version 4.0.5
2: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': Timeout of 60 seconds was reached
```
I don't what it meant. "if (max(r)) == package_versions("3.6"))"
```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/liuyunhe/anaconda3/envs/R4/lib/libopenblasp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.16 compiler_4.0.3
```

**Comment by Seraph-009** [comment]
is it the problem with the version of R?

**Comment by vjcitn** [comment]
I cannot reproduce this.  The timeout seems the most important event.  If you cannot get config.yaml, BiocManager won't be able to figure out how to map your R to Bioconductor versions. `max(r)` won't work.  Probably BiocManager should be bulletproofed at that point -- @LiNk-NY 

If I am wrong about that, it may have something to do with conda, which we do not use for core development and distribution. For R 4.0.3, the suitable version of BiocManager is seems to be 1.30.10, as that is what the Rstudio packagemanager supplies with the associated rocker/verse docker image.

**Comment by lshep** [comment]
You need to be currently need to have internet access to use BiocManager; please make sure you are connected to the internet or if you are not follow the instructions for offline use  https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html#offline-use 
The default timeout for download time is set for 60 sec.  If you are connected to the internet and still receive a timeout error consider increasing your timeout limit with  `options(timeout=300L)`

**Comment by LiNk-NY** [comment]
> I cannot reproduce this. The timeout seems the most important event. If you cannot get config.yaml, BiocManager won't be able to figure out how to map your R to Bioconductor versions. `max(r)` won't work. Probably BiocManager should be bulletproofed at that point -- @LiNk-NY

I am also unable to reproduce and it's hard to debug this timeout. 
My hunch is that `txt` is an empty string after the timeout and should be caught before the rest of the code continues via something like:

```r
    if (!length(txt) || inherits(txt, "error"))
        return(.VERSION_MAP_SENTINEL)
```

**Comment by hpages** [comment]
Kind of the same story as [here](https://github.com/Bioconductor/BiocManager/issues/131#issuecomment-1112544882).

More generally speaking, the code in **BiocManager** should defend itself against the possibility of bad things happening when trying to fetch the online yaml config file.

**Comment by lshep** [comment]
And I had the same issue with people trying to use the hubs offline as well and had to point them to using BiocManager offline.
