### ISSUE TITLE
BiocManager::install(version = "3.15", ask = FALSE, force = TRUE) error

### ISSUE THREAD

**Issue by xec-cm** [Bioconductor/BiocManager#146]
When executing `BiocManager::install(version = "3.15", ask = FALSE, force = TRUE)` in github actions, it fails on windows and mac-os machines but not on ubuntu.

The error was: 

![image](https://user-images.githubusercontent.com/70643921/207893566-b43be66c-06dc-4c78-8a8d-0a5075c10c80.png)

[Link to github action report](https://github.com/MicrobialGenomics-IrsicaixaOrg/dar/actions/runs/3705329646/jobs/6279096453)

Thanks

**Comment by LiNk-NY** [comment]
https://github.com/Bioconductor/BiocManager/issues/142
