### ISSUE TITLE
BiocManager::install => no example of downloading specific package versions

### ISSUE THREAD

**Issue by nick-youngblut** [Bioconductor/BiocManager#153]
At least for BiocManger 1.30.19, there is no example in the `BiocManager::install` function docs on how to download a specific package version:

```
## Not run: 
## update previously installed packages
BiocManager::install()

## install Bioconductor packages, and prompt to update all
## installed packages
BiocManager::install(c("GenomicRanges", "edgeR"))

## install a CRAN and Bioconductor packages:
BiocManager::install(c("survival", "SummarizedExperiment"))

## install a package from source:
BiocManager::install("IRanges", type="source")

## End(Not run)
```

Given the importance of reproducibility in data science, it would be helpful if the docs included instructions on installing a specific package version.

**Comment by lshep** [comment]
Normally it is advisable to use the latest version of a package or the frozen version of a package for a particular R/Bioc;  understanding the importance of reproducibility I would argue this belongs in a specialized section perhaps in the vignette or elsewhere as it should not be used daily or by users not understanding the consequences of such an action as it could introduce an invalid installation if not using coordinated versions of Bioconductor / R .

**Comment by nick-youngblut** [comment]
I guess that this is a structural issue with CRAN and Bioconductor, in the fact that one cannot simply specify a package version as with python (pip or conda). Maybe not much be done there, but I definitely agree with you that creating a vignette on installing a specific version (with possibly a link to the vignette in the `BiocManager::install` function docs) would be great!

**Comment by LiNk-NY** [comment]
Hi Nick, @nick-youngblut 

Welcome to Bioconductor! Bioconductor is more rigorous than specifying a single version of a package. The Bioconductor releases hold fixed a set number of package versions that were tested with a specific version of R. If you'd like to use a particular package's version, you'd have to find the release it was published in e.g., `S4Vectors` version `0.34.0` was published in Bioconductor Release `3.15` with R version `4.2` . You could then install it and (all the packages that were tested with it) via `BiocManager::install("S4Vectors")` in an R session that runs `4.2`. 

This is not the typical use case in Bioconductor, thus we don't have tools to search for the Bioconductor release number given a package's version number. You would have to search through the releases manually here: https://www.bioconductor.org/about/release-announcements/

If you'd like to extend the reproducibility to CRAN packages, consider using [`BiocArchive`](https://github.com/LiNk-NY/BiocArchive) which is still in development and will allow you to use snapshots of CRAN from either RSPM or MRAN.

**Comment by nick-youngblut** [comment]
> The Bioconductor releases hold fixed a set number of package versions that were tested with a specific version of R

I've contributed many R packages to conda-forge (and bioconda), which allows for some flexibility of particular R-version + particular package-version, but those conda recipes are far less rigorously tested versus the CRAN/Bioconductor approach. Still, I appreciate the simplicity of `mamba env create -n my_R_env -f list_of_packages.yml`. The downside of the conda approach is the general lack of cross-language support (python <-> R), but Posit is starting to change that.

**Comment by lshep** [comment]
Which is why we don't always support or can help with issues when bioconda is used for Bioconductor packages as there can be significant differences on how a package runs when from one version of R to another (thinking in particular the switch from R 3.6 to R 4.0)
