### ISSUE TITLE
Unable to use do_query() function

### ISSUE THREAD

**Issue by digs1998** [Bioconductor/BiocManager#155]
I have installed BiocManager version 3.16 as per the documentation provided online however when I am trying to use the do_query() function for fetching datasets, it throws this error.

`Error in do_query(context = "study", input_item = "study", input_value = "Cystic Fibrosis",  : 
  could not find the function "do_query"`

How do I resolve this?

**Comment by LiNk-NY** [comment]
Hi @digs1998 
`BiocManager` does not have a `do_query` function. You have the wrong package. 
Best,
Marcel
