### ISSUE TITLE
I can't run DECIPHER::IdClusters

### ISSUE THREAD

**Issue by julietaalvarez** [Bioconductor/BiocManager#156]
I am trying to run this line:
`clusters <- DECIPHER::IdClusters(
  d, 
  method = "complete",
  cutoff = 0.03, # use `cutoff = 0.03` for a 97% OTU 
  processors = nproc)`
but I received "**Error: 'IdClusters' is not an exported object from 'namespace:DECIPHER**'"
I tried to install several times DECIPHER with this `BiocManager::install("DECIPHER")` and it does not mark any error in the installation. I am using R 4.2.2. 
Is anybody having the same trouble?

**Comment by LiNk-NY** [comment]
Hi @julietaalvarez 
This is a good question but it is not a `BiocManager` issue and please post on the support.bioconductor.org website. 
Best regards,
Marcel
