### ISSUE TITLE
confusing information in "See Also"

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocManager#16]
The text in `?BiocManager::install` seems to imply that users should use `install.packages()` to install packages and `update.packages()` to update packages, rather than using `BiocManager::install()`.

```
See Also

BiocManager::repositories() returns the Bioconductor and CRAN repositories used by install().

install.packages() installs the packages themselves.

update.packages() updates all installed packages.

chooseBioCmirror() allows choice of a mirror from all public Bioconductor mirrors.

chooseCRANmirror() allows choice of a mirror from all public CRAN mirrors.
```

**Comment by LiNk-NY** [comment]
Hi Levi, @lwaldron 
Does this work? Let me know if you'd like me to add more. 
Regards,
Marcel

**Comment by lwaldron** [comment]
Yes, that's clear now.
