### ISSUE TITLE
site_repository not permanent

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#162]
Hi Martin, @mtmorgan 
Should there be an option / environment variable that allows one to more permanently set `site_repository` for the `install` function?
Thanks!
-Marcel

**Comment by mtmorgan** [comment]
Sure; I guess actually it would be in `repositories()` and would use the option / environment variable when `!nzchar(site_repository)`. 

I'm not sure where options / environment variables are documented? On `?BiocManager`?

**Comment by LiNk-NY** [comment]
See this branch :  https://github.com/Bioconductor/BiocManager/tree/site_repo_optenv

**Comment by LiNk-NY** [comment]
Resolved in fe8b5ec1c524058f26b158b79242d5bc22564096
