### ISSUE TITLE
Issue while using phyloseq with Bioconductor / SSL connect error

### ISSUE THREAD

**Issue by sroblet** [Bioconductor/BiocManager#175]
Hi, 

i have used the package phyloseq for several months and everything was fine until last week when i had to download the last version of R. Now i can not use bioconductor anymore for some reasons... I have spend the whole day trying to fix this issue using your forum without success. I also tried to unistall and reinstall R, Rstudio and Rtools but the issue still remaining. Another strange thing is that when i try to type 'https://bioconductor.org/config.yaml' on a web browser (either firefox or google chrome) this message appears : "err_connection_closed" so may be it is not an issue with R but with my laptop. I asked collegues from my lab and it worked perfeclty fine for them even if we all use the same wifi connection.

Here is the message error i got on R studio : 

```
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")


Bioconductor version cannot be validated; no internet connection?  See #troubleshooting section in vignette
Warning messages:
1: In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL connect error'
2: In readLines(...) : line 6 appears to contain an embedded nul
3: In readLines(...) :
  incomplete final line found on 'http://bioconductor.org/config.yaml'



sessionInfo( )
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
```

Thanks a lot for your help :)

**Comment by mtmorgan** [comment]
That `https://bioconductor.org/config.yaml` does not work in a browser points to a problem with your laptop configuration or internet access. It could be that there is a proxy, or it could be that your IT department is limiting access in some way. Work with your IT department to solve this problem ('how do I access https://bioconductor.org/config.yaml in my browser') and it is likely that it will point to the solution with R.

**Comment by sroblet** [comment]
Thanks for your fast response :)  I will try to have a look with my IT department next week.
I just dont get why this happened now (it was working perfecly fine some weeks ago) and why my collegues can run it even if they have to the same internet access/config/IT restrictions..

**Comment by LiNk-NY** [comment]
The issue seems to be due to an internet connection / proxy / firewall setting. Feel free to re-open if otherwise. :)
