### ISSUE TITLE
version: Bioconductor version cannot be validated; no internet connection? 

### ISSUE THREAD

**Issue by 15993561663** [Bioconductor/BiocManager#177]

**Comment by 15993561663** [comment]
Please help me

**Comment by 15993561663** [comment]
version: Bioconductor version cannot be validated; no internet connection?

**Comment by lshep** [comment]
You need a valid internet connection to properly use BiocManager.  If you do not have internet connection see the [vignette section on offline use](https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html#offline-use)

**Comment by LiNk-NY** [comment]
This is likely due to be a firewall issue. Consider using a mirror that is close to your location. 
I am assuming this is resolved since you opened #178 ..

**Comment by isbool** [comment]
Hey when trying to install it on webR i get the above error
