### ISSUE TITLE
I can't download BiocManager but has been download

### ISSUE THREAD

**Issue by 15993561663** [Bioconductor/BiocManager#178]
install.packages("BiocManager")

  There is a binary version available but the source
  version is later:
             binary  source needs_compilation
BiocManager 1.30.16 1.30.22             FALSE

installing the source package ‘BiocManager’

trying URL 'http://mirrors.ustc.edu.cn/CRAN/src/contrib/BiocManager_1.30.22.tar.gz'
Content type 'application/octet-stream' length 582690 bytes (569 KB)
downloaded 569 KB

* installing *source* package 'BiocManager' ...
** 成功将'BiocManager'程序包解包并MD5和检查
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'BiocManager'
    finding HTML links ... 好了
    BiocManager-pkg                         html  
    available                               html  
    install                                 html  
    repositories                            html  
    valid                                   html  
    version                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Warning in file(con, "r") : InternetOpenUrl失败:’操作超时'
Warning in file(con, "r") : InternetOpenUrl失败:’操作超时'
*** arch - x64
What should i do? Thanks in advance.

**Comment by lshep** [comment]
have you tried a different CRAN mirror?

**Comment by LiNk-NY** [comment]
@15993561663 
Can you provide the full output and `sessionInfo()`?

**Comment by 15993561663** [comment]
Thanks a lot. I use the other Internet and it does work.
&nbsp;


关帅埔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 晚上7:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Bioconductor/BiocManager] I can&#39;t download BiocManager but has been download (Issue #178)





 
have you tried a different CRAN mirror?
