### ISSUE TITLE
'getOption("repos")' replaces Bioconductor standard repositories

### ISSUE THREAD

**Issue by 15993561663** [Bioconductor/BiocManager#179]
BiocManager::install("simpleaffy")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.qlu.edu.cn/CRAN
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing package(s) 'simpleaffy'
> BiocManager::install("simpleaffy",force = TRUE)
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.qlu.edu.cn/CRAN
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing package(s) 'simpleaffy'
> library(simpleaffy)
Error in library(simpleaffy) : there is no package called ‘simpleaffy’
Give me a favor. Thanks a lot

**Comment by LiNk-NY** [comment]
Hi @15993561663 
`simpleaffy` has been removed from Bioconductor 
See the page: https://bioconductor.org/about/removed-packages/
