### ISSUE TITLE
devel docker and BiocManager

### ISSUE THREAD

**Issue by lshep** [Bioconductor/BiocManager#18]
So I updated the devel docker for BiocManager but for the last two weeks it has failed. The script that is running is found [here](https://github.com/Bioconductor/bioc_docker/blob/master/out/devel_base/install.R)

It seems to install and load fine but then I get an ERROR when trying to change the version still

```
> 
library(BiocManager)

> 


> 
if(BiocManager::version() != "3.8"){

+ 
    BiocManager::install(version="3.8",

+ 
                         update=TRUE, ask=FALSE)

+ 
}

[91mError: $ operator is invalid for atomic vectors
[0m
[91mExecution halted
[0m

```
The docker build report is found [here](https://hub.docker.com/r/bioconductor/devel_base2/builds/bkbljxzfrsnl57bs4izwkrb/)

Any advice is appreciated.

**Comment by LiNk-NY** [comment]
Hi Lori, @lshep 
I'm looking into this. This could be due to trying something like
`c(CRAN = "my/repo/location")$CRAN` in the code. 

I will investigate further. 
In the meantime, could you try adding something like:
```r
options( repos = c(CRAN = "https://cloud.r-project.org")
```
in the `~/.Rprofile`? 

Best regards,
Marcel

**Comment by lshep** [comment]
I think it might be related to the report issue #21

**Comment by LiNk-NY** [comment]
Yes, thanks for reporting it Lori @lshep. 
I've added a patch to the code. See 86471ba2c50faa07940840fbc7478dd20eb7defb
