### ISSUE TITLE
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  :    Viewport has zero dimension(s)

### ISSUE THREAD

**Issue by 15993561663** [Bioconductor/BiocManager#180]
group_list=c(rep('control',18),rep('T',18))
> group_list=factor(group_list)
> group_list <- relevel(group_list, ref="control")
> library(limma) 
> exp.5=normalizeBetweenArrays(exp.4)
> design=model.matrix(~ group_list)
> colnames(design) <- levels(group_list)
> rownames(design) <- colnames(exp.5)
> fit=lmFit(exp.5,design)
> fit=eBayes(fit) 
> allDiff=topTable(fit,coef=2,adjust='fdr',number=Inf) 
> library(ggplot2)                         
> 
> library(ggrepel)  
> data<-allDiff
> data$significant="stable"
> data$significant[data$logFC>=0.585 & data$P.Value <0.05]="up"
> data$significant[data$logFC<= -0.585 & data$P.Value <0.05]="down"
> select.FPKM <- (data$AveExpr > 5 )
> select.log2FC <- abs(data$logFC) >0.5
> select.qval <- (data$adj.P.Val< 0.05)
> select.vec=(select.FPKM & select.log2FC & select.qval) 
> degs.list=as.character(rownames(data))[select.vec]
> label.deg=sample(degs.list,20)
> p=ggplot(data,aes(logFC,-1*log10(P.Value)))+xlim(-2,2)+ylim(0,6)+
+   geom_point(aes(color=significant),size=0.8)+theme_classic()+
+   scale_color_manual(values = c("#2a9d8f","#EE7AE9","#f8961e"))+
+   geom_hline(yintercept = 1.3,linetype=4,size=0.3)+
+   geom_vline(xintercept = c(-0.5,0.5),linetype=4,size=0.3)+
+   theme(title=element_text(size = 18),text = element_text(size=18))+
+   labs(x="log2(foldchange)",y="-log10(p_value)")
> data_selected <- data[label.deg,]
> p + geom_label_repel(data=data_selected,
+                      aes(label=rownames(data_selected)))
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)

**Comment by PeteHaitch** [comment]
Don't post random, poorly formatted output as a GitHub issue with zero explanation of what you are trying to do to a GitHub repository that has nothing to do with your code.

Questions about Bioconductor packages should be posted to https://support.bioconductor.org/.
You should read the posting guide (https://bioconductor.org/help/support/posting-guide/) before asking questions there or elsewhere.

**Comment by LiNk-NY** [comment]
Thanks Pete!
