### ISSUE TITLE
error in  addGroupCoverages(ArchRProj = mp, groupBy = "Sample")

### ISSUE THREAD

**Issue by yangchao4** [Bioconductor/BiocManager#181]
Hello, I found an error in this    mp<-addGroupCoverages(ArchRProj = mp, groupBy = "Sample")   command.
[AchR-add.txt](https://github.com/Bioconductor/BiocManager/files/12457366/AchR-add.txt)

Here is the log file and the error message in the log file
2023-08-29 01:46:54 : ERROR Found in .addKmerBiasToCoverage for  
LogFile = ArchRLogs/ArchR-addGroupCoverages-27656847528052-Date-2023-08-29_Time-01-46-16.log

<simpleError in h(simpleError(msg, call)): 在为'start'函数选择方法时评估'x'参数出了错: 找不到对象'fancy_mseq' >

2023-08-29 01:46:54 : errorList, Class = list

errorList$y: length = 1
[1] 1

errorList$coverageFile: length = 1
                                                                                         j2._.Rep1 
"/home/zeyy/dev/sdf/mouse/atac_analysis/mp/GroupCoverages/Sample/j2._.Rep1.insertions.coverage.h5" 

errorList$chr: length = 1
[1] "chr10"

errorList$iS: length = 1
[1] "Error .getCoverageInsertionSites"

I don't know how to solve this problem. Could you please take a look and help me? Thank you very much.

**Comment by LiNk-NY** [comment]
Hi @yangchao4 
This is not the appropriate repository for asking your question. Please see the package's issues URL. 
Best,
Marcel
