### ISSUE TITLE
Using on Shiny and deploying on Posit

### ISSUE THREAD

**Issue by natyfp** [Bioconductor/BiocManager#185]
Hi, I'm trying to deploy an app using BiocManager, but I'm having this error:
HTTP 404 https://bioconductor.org/packages/3.18/data/annotation/src/contrib/Archive/BiocVersion/BiocVersion_3.18.1.tar.gz

On the manifest is like this:
"BiocVersion": {
      "Source": "Bioconductor",
      "Repository": "https://bioconductor.org/packages/3.18/bioc",
      "description": {
        "Package": "BiocVersion",
        "Version": "3.18.1",
        "Title": "Set the appropriate version of Bioconductor packages",
        "Description": "This package provides repository information for the appropriate\n    version of Bioconductor. ",
        "Authors@R": "c(\n    person(\"Martin\", \"Morgan\", email = \"martin.morgan@roswellpark.org\",\n        role = \"aut\"),\n    person(\"Marcel\", \"Ramos\", email = \"marcel.ramos@roswellpark.org\",\n        role = \"ctb\"),\n    person(\"Bioconductor\", \"Package Maintainer\",\n        email  = \"maintainer@bioconductor.org\",\n        role = c(\"ctb\", \"cre\")))",
        "biocViews": "Infrastructure",
        "Depends": "R (>= 4.3.0)",
        "License": "Artistic-2.0",
        "Encoding": "UTF-8",
        "RoxygenNote": "6.0.1",
        "git_url": "https://git.bioconductor.org/packages/BiocVersion",
        "git_branch": "RELEASE_3_18",
        "git_last_commit": "70680b8",
        "git_last_commit_date": "2023-11-15",
        "Date/Publication": "2023-11-15",
        "NeedsCompilation": "no",
        "Packaged": "2023-11-15 22:20:45 UTC; biocbuild",
        "Author": "Martin Morgan [aut],\n  Marcel Ramos [ctb],\n  Bioconductor Package Maintainer [ctb, cre]",
        "Maintainer": "Bioconductor Package Maintainer <maintainer@bioconductor.org>",
        "Built": "R 4.3.2; ; 2023-11-16 13:41:25 UTC; windows"
      }
    }

Should something be different?

**Comment by LiNk-NY** [comment]
Hi Natallya, @natyfp 

Whatever is deploying (`renv`?) to Posit is using the wrong link (hence the 404 error). 

The tarball for the `BiocVersion` package is at this location:
https://bioconductor.org/packages/3.18/bioc/src/contrib/BiocVersion_3.18.1.tar.gz

usually 

```r
options(repos = BiocManager::repositories())
```

within the `server.R` does the trick. 
For shiny app deployment related issues, please ask at https://community.rstudio.com/

Best,
Marcel
