### ISSUE TITLE
install(version=...) fails when .valid() returns TRUE

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocManager#21]
This line https://github.com/Bioconductor/BiocManager/blob/dae68087d6cc0bd3e3aaff5332840ac889f226a6/R/install.R#L348 can fail because it expects a list of too old / too new packages, but instead can get TRUE in the previous line.

**Comment by lshep** [comment]
I think this might be what is the problem on the devel_base docker as well.
