### ISSUE TITLE
Testing in R-devel / Oldrel for CRAN

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocManager#3]
Hi Martin, @mtmorgan

Perhaps the package should not error out when testing with R-devel / Old-release? 
It will get tested using these R versions.

For example: https://cran.r-project.org/web/checks/check_results_ggplot2.html

Regards,
Marcel

**Comment by mtmorgan** [comment]
Can you be more specific? The package really does want to specify an R version dependency...

**Comment by LiNk-NY** [comment]
@mtmorgan
I was just thinking about the versions that `BiocManager` will be tested on and
the results of those tests (as shown in the link above). 
I think we can just let it fail for non-supported versions such as R-devel (>= 3.6.0).

**Comment by mtmorgan** [comment]
Can you clarify why it fails under R-devel?

**Comment by LiNk-NY** [comment]
At least for R-devel, Bioconductor _can't_ be installed.
Therefore, there is no way to obtain `BiocVersion` for the package to be checked via `R CMD check`.

**Comment by LiNk-NY** [comment]
Perhaps `BiocVersion` should be under the `Enhances:` field?

**Comment by LiNk-NY** [comment]
I wasn't able to find reproducible code from the CRAN builders but based on the results, packages in `Suggests:` are not required when running `R CMD check`. This will be a non-issue. 
https://win-builder.r-project.org/b9G8xAgVZYDX/00check.log
Thanks.
