### ISSUE TITLE
BiocManager::valid() not working within reprex::reprex()

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BiocManager#4]
Running from a new R session:

```R
> BiocManager::valid()

* sessionInfo()

R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] repete_0.0.0.9011 devtools_1.13.5  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17           lobstr_0.0.0.9000     
 [3] XVector_0.21.2         magrittr_1.5          
 [5] GenomicRanges_1.33.6   BiocGenerics_0.27.0   
 [7] zlibbioc_1.27.0        IRanges_2.15.14       
 [9] munsell_0.5.0          colorspace_1.3-2      
[11] rlang_0.2.1            stringr_1.3.1         
[13] GenomeInfoDb_1.17.1    plyr_1.8.4            
[15] tools_3.5.0            parallel_3.5.0        
[17] withr_2.1.2            fortunes_1.5-4        
[19] yaml_2.1.19            digest_0.6.15         
[21] GenomeInfoDbData_1.1.0 BiocManager_1.29.45   
[23] pryr_0.1.4             S4Vectors_0.19.12     
[25] bitops_1.0-6           codetools_0.2-15      
[27] RCurl_1.95-4.10        memoise_1.1.0         
[29] stringi_1.2.3          compiler_3.5.0        
[31] scales_0.5.0           stats4_3.5.0          

Bioconductor version '3.8'

  * 0 packages out-of-date
  * 2 packages too new

create a valid installation with

  BiocManager::install(c(
    "hms", "reprex"
  ), update = TRUE, ask = FALSE)

Warning message:
0 packages out-of-date; 2 packages too new 
```

Running as `reprex::reprex(x = BiocManager::valid())`:

``` r
BiocManager::valid()
#> Error in repos[["CRAN"]]: subscript out of bounds
```

Created on 2018-06-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Any ideas? The combo of `reprex::reprex()` and `BiocManager::valid()` will be valuable when asking for minimal bug reports.

**Comment by LiNk-NY** [comment]
Hi Pete, @PeteHaitch 
This seems like an issue with the options not being used in the package.
I'm not sure where in the `reprex` package these options get lost. 

``` r
options("repos"); BiocManager::valid()
#> $repos
#> [1] "https://cloud.r-project.org" "https://cloud.r-project.org"
#> Error in repos[["CRAN"]]: subscript out of bounds
#> $repos
#> [1] "https://cloud.r-project.org" "https://cloud.r-project.org"
```

Created on 2018-07-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by PeteHaitch** [comment]
Are you saying you think it's a **reprex** issue rather than a **BiocManager** issue? If so, I'll report it there.

**Comment by LiNk-NY** [comment]
Hi Pete, @PeteHaitch 
Basically, the package creates a clean environment from which the example code is run
(in order to ensure reproducibility). 
This is more of a feature of the package although they should have a way of
setting options as part of the `reprex`. Perhaps there is a way but I'm not familiar with the package. 
@jennybc can surely provide insights. 

Regards,
Marcel

**Comment by jennybc** [comment]
> they should have a way of setting options as part of the reprex

To answer this question, there is a way to do this in a call and, if it proves necessary, I can put that optionally under the control of an option, as is true for many other args. But I suspect we can and should solve this another way.

But here is a demo of how to change the `repos` option at reprex time, in case you want to try that and confirm that this is the only thing keeping reprex and `BiocManager::valid()` from working well together.

This call:

``` r
reprex(
  options("repos"),
  opts_knit = list(repos = c(CRAN = "https://cran.rstudio.com/"))
)
```

produces this output

``` r
options("repos")
#> $repos
#> [1] "https://cran.rstudio.org"    "https://cloud.r-project.org"
```

Created on 2018-07-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by jennybc** [comment]
Hi @gaborcsardi do you have any insight?

**Comment by jennybc** [comment]
Maybe the names are being lost here:

https://github.com/cran/callr/blob/d591dfee954a3a87cdf690c5e4953c4782ec17cb/R/check.R#L27

Small demo:

``` r
(x <- c(getOption("repos"), c(CRAN = "whatever")))
#>                                                             
#>    "https://cran.rstudio.org" "https://cloud.r-project.org" 
#>                          CRAN 
#>                    "whatever"
as.character(x)
#> [1] "https://cran.rstudio.org"    "https://cloud.r-project.org"
#> [3] "whatever"
```

Created on 2018-07-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by gaborcsardi** [comment]
Indeed!

**Comment by LiNk-NY** [comment]
Yes, Jenny @jennybc that's right. 
The code in [`BiocManager:::.repositories_base`](https://github.com/Bioconductor/BiocManager/blob/master/R/repositories.R#L15) does `repos[["CRAN"]]` and since `callr::r_safe` strips the names, we get an error.

**Comment by LiNk-NY** [comment]
Thanks Jenny!

**Comment by PeteHaitch** [comment]
Can confirm this has fixed the original issue. Thanks all!
