### ISSUE TITLE
Issue installing packages from BiocManager 

### ISSUE THREAD

**Issue by ShaunyKins** [Bioconductor/BiocManager#40]
I am trying to download the R package "Rsubread" from BiocManager but i keep getting the same error message: 

Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.2 (2018-12-20)
Installing package(s) 'Rsubread'
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘Rsubread’
  These will not be installed
installation path not writeable, unable to update packages: class, codetools

This is the code I have used:

if (!requireNamespace("BiocManager"))
  +     install.packages("BiocManager", lib= "~/R/library")
BiocManager::install("Rsubread", version = "3.8")

BioManager seems to have installed successfully but none of the packages after that are installing. 

What can I do?
Cheer

**Comment by mtmorgan** [comment]
Please ask user support questions like this on the [support site][1].

I guess you're on Windows machine; Rsubread is only available for MacOS and Linux.

[1]: https://support.bioconductor.org
