### ISSUE TITLE
BiocManager::install() does not play nice with Microsoft R Application Network/Microsoft R Open

### ISSUE THREAD

**Issue by marcora** [Bioconductor/BiocManager#41]
When using Microsoft R Open (MRO v3.5.1) that has default CRAN repo set to 2018-08-01 snapshot of CRAN (https://mran.microsoft.com/timemachine), BiocManager::install() still tries to update packages to newest versions present in standard CRAN. This is not consistent with the MRO philosophy that promotes reproducibility by providing CRAN snapshots for each release. It would be great to support this R distribution in a way that is consistent with its philosophy.

**Comment by mtmorgan** [comment]
Bioconductor packages are built, tested, and distributed against current package versions, so offering to install against archived versions is not really consistent with project practices. This is explicitly captured in the BiocManager code https://github.com/Bioconductor/BiocManager/blob/0d509a650f33d437cd5eb2a597807384969d4ca3/R/repositories.R#L6-L20.

Arbitrary repositories can be put 'in front' of standard repositories using the `site_repository=` argument to either `install()` or `repositories()`, so you could point that argument to the Microsoft snapshot.

Philosophically, one could suggest that Microsoft R Open snapshot Bioconductor packages in the same manner as CRAN packages? Or perhaps this functionality is already available in Microsoft's checkpoint package? FWIW archived versions of Bioconductor packages are at, e.g., https://bioconductor.org/packages/3.8/bioc/src/contrib/Archive/.
