### ISSUE TITLE
Fail more informatively with non-interactive(), ask = FALSE updates

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocManager#47]
The current behavior indicates that the update failed, but does not indicate why, see https://support.bioconductor.org/p/120679/#120701

```
## BiocManager::install(version = "3.7")
Error: Bioconductor version not changed
Execution halted
```
Would rather see something like
```
Error: `install()` failed in non-interactive session; force installation with `install(..., ask = FALSE)`.
```

**Comment by LiNk-NY** [comment]
The `...` are not passed on to `.msg` correctly. That's why I had to use `paste0`. 
I will look more into it later.

**Comment by LiNk-NY** [comment]
The usual behavior is to pass a single string, although `...` implies more than one. 
Might not be worth supporting multiple strings. I've changed it to just one string. 

See [Bioconductor/BiocManager@errmsg](https://github.com/Bioconductor/BiocManager/tree/errmsg)

**Comment by mtmorgan** [comment]
.msg() / .stop() / .warning() are like sprintf() with a fmt string and substitutions, rather than like stop() etc which paste `...`.
