### ISSUE TITLE
Why R 3.6 can not install BiocManager 3.9 version?

### ISSUE THREAD

**Issue by wang950312** [Bioconductor/BiocManager#55]
These days I  can't use BiocManager on R 3.6.1, and alway shows that 

> "Bioconductor version '3.8' is out-of-date; the current release version '3.9' is available with R version '3.6'"

 But when I reinstall that package through CRAN, it is still version 3.8 and the Installation package is **BiocManager_1.30.4.tar.gz**

**Comment by wang950312** [comment]
I have found the way to update
`BiocManager::install(version="3.9") `

**Comment by LiNk-NY** [comment]
@wang950312 For future reference, please check the version of `BiocVersion` with `packageVersion("BiocVersion")`
-MR
