### ISSUE TITLE
The packages in Bioconductor 3.10 cannot be retrived by BiocManager::install()

### ISSUE THREAD

**Issue by kokitsuyuzaki** [Bioconductor/BiocManager#59]
Dear, BioC Core Team

I found that the packages released in BioC 3.10 cannot be retrieved by `BiocManager::install()`.
https://www.bioconductor.org/news/bioc_3_10_release/

For example, I tried to execute this code,
but the installation failed with warning message such as
`package ‘schex’ is not available (for R version 3.6.1)`.

```
BiocManager::install("schex")
BiocManager::install("scTGIF")
BiocManager::install("schex")
BiocManager::install("scDblFinder")
```

Actually, BiocManager cannot even recognize such packages; such packages are not listed in the output of `BiocManager::available()`.

```
install.packages("BiocManager")
avail <- BiocManager::available()
grep("scTGIF", avail)
grep("schex", avail)
grep("scDblFinder", avail)
```

Koki

```
sessionInfo()

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] ja_JP.UTF-8/ja_JP.UTF-8/ja_JP.UTF-8/C/ja_JP.UTF-8/ja_JP.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.6.1      tools_3.6.1
```

**Comment by mtmorgan** [comment]
This is likely because
```
BiocManager::version()
```
reports that you are using **Bioconductor** version 3.9; try
```
BiocManager::install(version="3.10")
```
This updates _all_ your Bioconductor packages, which could take a long time and interrupt reproducibility; see `browseVignettes("BiocManager")` for discussion of managing multiple versions.

I'll leave this issue open to improve the information provided when this situation arises, as it is a common confusion.

**Comment by kokitsuyuzaki** [comment]
Thanks @mtmorgan !
By performing `BiocManager::install(version="3.10")`,
these packages can be installed properly.
