### ISSUE TITLE
Add Depends: R (>= 3.2.1)

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocManager#62]
I was curious whether `BiocManager::install()` could be used for older versions of R/Bioc and I'm happy to see that it does.  I was under the impression one had to use `biocLite()` in such cases.  I started with R 3.6.0 and went backward.  I found that BiocManager requires R (>= 3.2.1).

Adding:
```
Depends: R (>= 3.2.1)
```
to the `DESCRIPTION` file would helpful for R-chivers.

Details: Trying with R 3.2.0, we get:

```sh
$ R
R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)
...

> install.packages("BiocManager")
Installing package into ‘/cbc2/data2/henrik/R/x86_64-unknown-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cloud.r-project.org/src/contrib/BiocManager_1.30.10.tar.gz'
Content type 'application/x-gzip' length 40205 bytes (39 KB)
==================================================
downloaded 39 KB

* installing *source* package ‘BiocManager’ ...
** package ‘BiocManager’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onAttach failed in attachNamespace() for 'BiocManager', details:
  call: .version_map_get_online_config(config)
  error: could not find function "startsWith"
Error: loading failed
Error during wrapup: could not find function ".traceback"
Execution halted
ERROR: loading failed
* removing ‘/cbc2/data2/henrik/R/x86_64-unknown-linux-gnu-library/3.2/BiocManager’
```

**Comment by mtmorgan** [comment]
I'm not aware of a systematic way to know that the code works, as opposed to, e.g., installs (as above) and frankly do not trust the unit tests to fully cover the complicated logic that occurs in the web that is the history of Bioconductor release practices.

Minimally, is there a convenient systematic way to perform cross-platform build & check against prior versions of R?

**Comment by HenrikBengtsson** [comment]
I'm thinking about `Depends: R (>= 3.2.1)` as a lower bound.

> Minimally, is there a convenient systematic way to perform cross-platform build & check against prior versions of R?

I'd do use CI that runs `R CMD check` on BiocManager and then some different `BiocManager::install()` tests.  Adding code-coverage testing via 'covr' will help cover more logic.

These days, I'd go with GitHub Actions, which supports all OSes and lots of R versions (not sure how far back and resolution).  Although I doubt that's an issue here, maximum runtime is much larger that other CI services.  I just set this up for [future.tests](https://github.com/HenrikBengtsson/future.tests/blob/develop/.github/workflows/R-CMD-check.yaml) - it's straightforward.  See https://github.com/r-lib/actions and https://speakerdeck.com/jimhester/github-actions-for-r - I heard that guy is really brilliant :p

**Comment by hpages** [comment]
GitHub Actions looks good. Thanks Henrik for the tip and links. Who would have known something good would come out from the Microsoft acquisition! ;-)
