### ISSUE TITLE
Not able to install DECIPHER in R version 3.6.3

### ISSUE THREAD

**Issue by ismailsen32** [Bioconductor/BiocManager#65]

**Comment by mtmorgan** [comment]
This 'works for me'

```
> sessionInfo()
R version 3.6.3 Patched (2020-02-29 r77906)
Platform: x86_64-apple-darwin17.7.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /Users/ma38727/bin/R-3-6-branch/lib/libRblas.dylib
LAPACK: /Users/ma38727/bin/R-3-6-branch/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.6.3      tools_3.6.3
> BiocManager::install("DECIPHER")
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.3 Patched (2020-02-29
  r77906)
Installing package(s) 'DECIPHER'
trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/DECIPHER_2.14.0.tar.gz'
Content type 'application/x-gzip' length 12595057 bytes (12.0 MB)
==================================================
downloaded 12.0 MB

* installing *source* package ‘DECIPHER’ ...
** using staged installation
** libs
gcc -I"/Users/ma38727/bin/R-3-6-branch/include" -DNDEBUG  -I"/Users/ma38727/Library/R/3.6/Bioc/3.10/library/Biostrings/include" -I"/Users/ma38727/Library/R/3.6/Bioc/3.10/library/S4Vectors/include" -I"/Users/ma38727/Library/R/3.6/Bioc/3.10/library/IRanges/include" -I"/Users/ma38727/Library/R/3.6/Bioc/3.10/library/XVector/include" -I/usr/local/include  -fPIC  -g -O0  -c AlignProfiles.c -o AlignProfiles.o
...
```

Can you please provide more information, including the output of `sessionInfo()` and the specific problem you encounter?

**Comment by ismailsen32** [comment]
Thank you for your reply.
I would like to install "(seqinr), (adegenet), (ape), (ggtree) and (DECIPHER) in R 3.6.3. 
But I could not install ggtree and DECIPHER.
I showed the question about ggtree in github and I installed it. 
So I asked that question.
Also, I am new on the R and I have not installed it yet :

**Comment by mtmorgan** [comment]
Show us (copy and paste the commands you are using, and the output they generate, into a comment, like I did for my own session. Use a screen shot if necessary. Focus on one problem at a time, so show us what you are doing to install DECIPHER.

**Comment by ismailsen32** [comment]
I installed it with using "BiocManager::install("DECIPHER")".
Thank you again.

**Comment by mtmorgan** [comment]
Yes, but you said you had a problem. What is the problem?

**Comment by ismailsen32** [comment]
The problem was "Not able to install DECIPHER in R version 3.6.3". 
So it had solved. Now I try to import my file and use these packages ((seqinr), (adegenet), (ape), (ggtree) and (DECIPHER)).
Thank you for your fast reply.

**Comment by mtmorgan** [comment]
OK I see that you say that the problem with installing DECIPHER has been solved. I will close the issue.
