### ISSUE TITLE
Error on BiocManager::install('seandavi/sars2pack')

### ISSUE THREAD

**Issue by mymil** [Bioconductor/BiocManager#67]
`BiocManager::install('seandavi/sars2pack')`
produces the following message, including error:
```
Installing github package(s) 'seandavi/sars2pack'
Error: package 'remotes' not installed in library path(s)
    C:/Users/jwasserman/Documents/R/win-library/3.6
    C:/Program Files/R/R-3.6.1/library
install with 'install("remotes")'
```

Should {BiocManager} import {remotes}? If not, should error message read `install with 'install.packages("remotes")'` instead of current message?

**Comment by mtmorgan** [comment]
Remotes provides supplemental functionality, and is appropriately listed in the Suggests: field. See https://github.com/Bioconductor/BiocManager/commit/0f4c6472fa8a77501d4b9acb5784cc2beb9e6469 for an updated error message, which has not yet been released to CRAN.
