### ISSUE TITLE
implement BiocManager::install(".")

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocManager#79]
In testing workflows e.g. in GitHub Actions, there's sometimes a need to install from the current working directory, whether that be the master branch, other branch, pull request, etc. Currently people are accomplishing this with `remotes::install_deps()`:

https://github.com/seandavi/BuildABiocWorkshop2020/blob/a02e361ed08ad06c020c33b152b30ab590681e86/.github/workflows/basic_checks.yaml#L39

and with `devtools::install()`:

https://github.com/seandavi/BuildABiocWorkshop2020/blob/a02e361ed08ad06c020c33b152b30ab590681e86/Dockerfile#L9

both using the argument `repos = BiocManager::repositories()`. Is it possible to support these use cases the "Bioconductor Way" with `BiocManager::install()`, or are the above the recommended way to install a package from the local filesystem?

**Comment by mtmorgan** [comment]
My feeling is that BiocManager should be enabling 'best practices' for the user community, and installing packages from local sources (and even github, so I regret a little the support for github installation) does not fall under that remit.
