### ISSUE TITLE
valid() fails with an error if PACKAGES.gz but not PACKAGES is available

### ISSUE THREAD

**Issue by axelklenk** [Bioconductor/BiocManager#80]
Hi, 
I have set up a site repository for my company on a Sonatype Nexus Repository Manager (because this is what my Java-writing colleagues are using) which automatically generates a PACKAGES.gz but not a PACKAGES file for the repo.  This works fine with the `install/update/available.packages()` functions from `utils` and also with `BiocManager::install()` but not with `BiocManager::valid()`, probably because of the way URLs are constructed in function `.repositories_filter`.

**Comment by LiNk-NY** [comment]
Hi Axel, @axelklenk 

I think this is a standard location for the `PACKAGES` file and should not be changes. 

Martin @mtmorgan can comment more on this. 
Best, 
Marcel

**Comment by axelklenk** [comment]
Hi Marcel @LiNk-NY ,

sorry if I was unclear -- my point is not about the location (that's fine) but about the fact that it throws an error when the uncompressed file PACKAGES is missing even if the gzipped PACKAGES.gz is present and could be used.

Admittedly I have not checked what the documented behavior is :-) but since the standard R package management functions from package `utils` can handle this case I thought it was worth reporting.

Cheers,

 - axel

**Comment by LiNk-NY** [comment]
Hi Axel, @axelklenk 

Thank you for clarifying. 

Given that `utils` supports this behavior, it would make sense that `BiocManager` support this as well.
The `read.dcf` function behaves the same on `PACKAGES` and `PACKAGES.gz`.  

Any thoughts, @mtmorgan ? 

Best,
Marcel

**Comment by hpages** [comment]
Having `PACKAGES.gz` should be enough. If `PACKAGES` is required (and used) even when `PACKAGES.gz` is available, then it defeats the purpose of the whole thing which is to minimize the size of the package index to download.
Note that `tools:::write_PACKAGES()` also generates `PACKAGES.rds` (it generates 3 files). I don't know if having only this one makes `available.packages()` and family happy (I didn't try this), but, if it does, then BiocManager should probably also support that.

**Comment by mtmorgan** [comment]
Sorry, I didn't see @LiNk-NY self-assignment, but does the version on the branch https://github.com/Bioconductor/BiocManager/tree/repositories-filter-patch address the problem? It looks for .rds, .gz, and no extension flavors of `PACKAGES`. This function was only used for `valid()` and `available()`; other functions, especially `install()`, primarily delegate to R directly and therefore have the underlying behavior of, e.g., `install.packages()`.

**Comment by axelklenk** [comment]
Sorry again, should have added:
```
> getOption("repos")
                                       IdorsiaR
"http://nexus.idorsia.com/repository/IdorsiaR/"
                                           CRAN
                   "https://stat.ethz.ch/CRAN/"

```

**Comment by mtmorgan** [comment]
This is an unrelated change, affecting all uses of BiocManager:

```
> options(repos = c(CRAN="https://stat.ethz.ch/CRAN"))
> BiocManager::repositories()
Error: 'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://stat.ethz.ch/CRAN
> options(BiocManager.check_repositories = FALSE)
> BiocManager::repositories()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://stat.ethz.ch/CRAN

                                                BioCsoft
           "https://bioconductor.org/packages/3.12/bioc"
                                                 BioCann
"https://bioconductor.org/packages/3.12/data/annotation"
                                                 BioCexp
"https://bioconductor.org/packages/3.12/data/experiment"
                                           BioCworkflows
      "https://bioconductor.org/packages/3.12/workflows"
                                                    CRAN
                             "https://stat.ethz.ch/CRAN"
```

**Comment by axelklenk** [comment]
Thanks again -- then it works ok for me. (see below).

```
> options(BiocManager.check_repositories = FALSE)
> BiocManager::repositories()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://stat.ethz.ch/CRAN/

                                                                     BioCsoft
           "http://bioconductor.statistik.tu-dortmund.de//packages/3.11/bioc"
                                                                      BioCann
"http://bioconductor.statistik.tu-dortmund.de//packages/3.11/data/annotation"
                                                                      BioCexp
"http://bioconductor.statistik.tu-dortmund.de//packages/3.11/data/experiment"
                                                                BioCworkflows
      "http://bioconductor.statistik.tu-dortmund.de//packages/3.11/workflows"
                                                                     IdorsiaR
                              "http://nexus.idorsia.com/repository/IdorsiaR/"
                                                                         CRAN
                                                 "https://stat.ethz.ch/CRAN/"
> BiocManager::valid()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://stat.ethz.ch/CRAN/


* sessionInfo()

R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10.5 compiler_4.0.0        tools_4.0.0

Bioconductor version '3.11'

  * 0 packages out-of-date
  * 1 packages too new

create a valid installation with

  BiocManager::install("BiocManager", update = TRUE, ask = FALSE)

more details: BiocManager::valid()$too_new, BiocManager::valid()$out_of_date

Warning message:
0 packages out-of-date; 1 packages too new
```

**Comment by axelklenk** [comment]
Somehow this didn't make it into BioC 3.12 or am I missing something? Should I not have closed the issue??

**Comment by LiNk-NY** [comment]
Hi @axelklenk 
`BiocManager` is hosted on CRAN. We recommend that you use the version that is working for you from GitHub until we update the `BiocManager` package on CRAN. Releases are tagged in the [`release` section](https://github.com/Bioconductor/BiocManager/releases).

**Comment by axelklenk** [comment]
Hi @LiNk-NY 
of course, you're right, it's CRAN and not BioC. Silly Me. Thanks for reminding me. I'll keep using the GitHub version until CRAN release.
