### ISSUE TITLE
BiocManager::install(version = "3.12") does not give an error on R 4.0.2

### ISSUE THREAD

**Issue by HenrikBengtsson** [Bioconductor/BiocManager#82]
AFAIU, Bioconductor 3.12 requires R (>= 4.0.3).  From http://bioconductor.org/install/

> The current release of Bioconductor is version 3.12; it works with R version 4.0.3. Users of older R and Bioconductor must update their installation ...

However, I just discovered, by mistake, that:

```r
> BiocManager::install(version = "3.12")
```

happily run on R 4.0.2.  Is this a bug?

Is it the [DESCRIPTION](https://github.com/Bioconductor/BiocVersion/blob/RELEASE_3_12/DESCRIPTION#L15) file **BiocVersion** that should be updated?

```diff
diff --git a/DESCRIPTION b/DESCRIPTION
index 9a7fd38..813c0bf 100644
--- a/DESCRIPTION
+++ b/DESCRIPTION
@@ -12,7 +12,7 @@ Authors@R: c(
         email  = "maintainer@bioconductor.org",
         role = c("ctb", "cre")))
 biocViews: Infrastructure
-Depends: R (>= 4.0.0)
+Depends: R (>= 4.0.3)
 License: Artistic-2.0
 Encoding: UTF-8
 LazyData: true
```

**Comment by mtmorgan** [comment]
We're operating under the (possibly delusional) view that R adopts semantic versioning, and that 4.0.* are 'bug fixes' that do not change the API. The phrase "works with R version 4.0.3" is meant to encourage users to nonetheless adopt the version that we actually tests our packages against. We won't change the `Depends:` specification for the reason outlined here.

Please close the issue if that explanation is sufficient (if not satisfactory for your particular concerns).

**Comment by HenrikBengtsson** [comment]
Thanks for clarifying.  I honestly thought R (>= 4.0.3) was a hard limit. Has this always been the case - I've got vague memories that in the past there's been critical bug fixes in patched releases needed by Bioc? 

Since the current statement on the website is ambiguous, maybe it could be updated to:

The current release of Bioconductor is version 3.12; it requires R version 4.0.0 or newer where R version 4.0.3 is highly recommended. Users of older R and Bioconductor must update their installation ...

PS. I brought this up after upgrading to 3.12 on R 4.0.2 by mistake and getting installation errors on http://bioconductor.org/packages/release/bioc/html/DAPAR.html; that package requires R (>= 4.0.3).  To be picky is the latter a mistake since Bioconductor 3.12 should be supported on R (>= 4.0.0)?

**Comment by HenrikBengtsson** [comment]
Moved to https://github.com/Bioconductor/bioconductor.org/issues/76.
