### ISSUE TITLE
Not able to install fantaxtic in R version 4.0.3

### ISSUE THREAD

**Issue by BirongZhang** [Bioconductor/BiocManager#84]

**Comment by BirongZhang** [comment]
Warning message:
package ‘fantaxtic’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by lshep** [comment]
fantaxtic does not appear to be on CRAN or Bioconductor.  The default BiocManager repositories are only CRAN and Bioconductor.  To install from github you would have to include the github link.  If this is the correction package you are looking for  https://github.com/gmteunisse/Fantaxtic   than  `BiocManager::install("gmteunisse/Fantaxtic") `  should do the trick.
