### ISSUE TITLE
Download of some libraries fail, even if URL link is working. Manual Install succeeds.

### ISSUE THREAD

**Issue by dformoso** [Bioconductor/BiocManager#87]
Hi there,

I'm on Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10). Installing the library BSgenome.Hsapiens.UCSC.hg38 using BiocManager fails, but it succeeds when done manually.

```
if (!requireNamespace("BiocManager"))
    install.packages("BiocManager")

BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
```

> Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
> 
> Installing package(s) 'BSgenome.Hsapiens.UCSC.hg38'
> 
> Warning message in download.file(url, destfile, method, mode = "wb", ...):
> "downloaded length 515473408 != reported length 721596676"
> Warning message in download.file(url, destfile, method, mode = "wb", ...):
> "URL 'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.3.tar.gz': Timeout of 60 seconds was reached"
> Error in download.file(url, destfile, method, mode = "wb", ...) : 
>   download from 'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.3.tar.gz' failed
> Warning message in download.packages(pkgs, destdir = tmpd, available = available, :
> "download of package 'BSgenome.Hsapiens.UCSC.hg38' failed"
> Old packages: 'data.table', 'ggplot2', 'rlang', 'rmarkdown', 'RODBC', 'usethis'

```
download.file("https://bioconductor.org/packages/3.12/data/annotation/src/contrib/BSgenome.Hsapiens.UCSC.hg38_1.4.3.tar.gz", 
              destfile = "BSgenome.Hsapiens.UCSC.hg38_1.4.3.tar.gz", 
              method="curl")
install.packages("BSgenome.Hsapiens.UCSC.hg38_1.4.3.tar.gz", repos = NULL, type = "source")

```

The above succeeds.

I have fund other people on the web having this issue. 
https://stackoverflow.com/questions/64621495/problem-installing-tximportdata-on-r-what-is-this-error-about

Hope that helps in fixing it. :-)

**Comment by mtmorgan** [comment]
The problem is this

> Timeout of 60 seconds was reached

And the solution is

```
options(timeout = 300L)
```
(5 minute timeout). See 4a5a04db9fdea81251ebaf052f90b8775b4d258a, which is not yet available via CRAN.
