### ISSUE TITLE
Unable to use BiocManager offline with `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS`

### ISSUE THREAD

**Issue by glin** [Bioconductor/BiocManager#93]
Hi, I just upgraded BiocManager to version 1.30.12 and started getting this error when using BiocManager offline with the `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS` option:

```r
> options(BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS = FALSE)

> BiocManager::repositories()
Error: Bioconductor version '3.12' requires R version 'NA'; use `BiocManager::install(version = '3.12')` with R version
  4.0; see https://bioconductor.org/install
```

For some reason the R version is reported as `NA`, but I'm definitely on R 4.0. `BiocManager::version()` also reports the right Bioconductor version:

```r
> getRversion()
[1] ‘4.0.3’

> BiocManager::version()
# [1] ‘3.12’
# Warning message:
# Bioconductor online version validation disabled; see ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
```

---

To reproduce this, you can use an online environment with the latest BiocManager installed (1.30.12), and an appropriate version of BiocVersion installed. Then start a fresh R session, and set the `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS` option:

```r
options(BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS = FALSE)

BiocManager::version()
# [1] ‘3.12’
# Warning message:
# Bioconductor online version validation disabled; see ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
```

And then try to run `repositories()` or `install()`:
```r
BiocManager::repositories()
# Error: Bioconductor version '3.12' requires R version 'NA'; use `BiocManager::install(version = '3.12')` with R version
#   4.0; see https://bioconductor.org/install

BiocManager::install()
# Error: Bioconductor version '3.12' requires R version 'NA'; use `BiocManager::install(version = '3.12')` with R version
#   4.0; see https://bioconductor.org/install
```

As a workaround, I'm able to use BiocManager offline just fine with the new `BIOCONDUCTOR_CONFIG_FILE` option.

**Comment by LiNk-NY** [comment]
Hi Greg, @glin 
Yes, you're to create a local version map using the `BIOCONDUCTOR_CONFIG_FILE` option for offline use. 
It looks like we have not thoroughly documented this option in the `?install` page. We will update that. Thanks!
Best,
Marcel

**Comment by glin** [comment]
@LiNk-NY Thanks for the clarification and doc update. As a follow up, is the `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS` option still meant to be used alongside the new `BIOCONDUCTOR_CONFIG_FILE` option? Or does `BIOCONDUCTOR_CONFIG_FILE` replace it?

If I try to configure `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS` at all (using the [vignette](https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html#offline-use) steps), I get that error message even with `BIOCONDUCTOR_CONFIG_FILE` configured.

For example, running this in a fresh R session:

```r
options(
  BIOCONDUCTOR_CONFIG_FILE = "https://bioconductor.org/config.yaml",  # or some other offline config.yaml
  BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS = FALSE
)

BiocManager::repositories()
# Error: Bioconductor version '3.12' requires R version 'NA'; use `BiocManager::install(version = '3.12')` with R version
#   4.0; see https://bioconductor.org/install
# In addition: Warning message:
# Bioconductor online version validation disabled; see ?BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS
```

Without `BIOCONDUCTOR_ONLINE_VERSION_DIAGNOSIS=FALSE`, offline use works fine with just `BIOCONDUCTOR_CONFIG_FILE` configured.

**Comment by LiNk-NY** [comment]
Thanks Greg for reporting this @glin.

Martin @mtmorgan, 

It looks like `.version_map` returns `NA`. Perhaps `BiocManager:::.version_validity` should handle `NA` somehow?
Or possibly allow the user to set the `BiocStatus` themselves. 

```r
> BiocManager:::.version_map_get_offline()
  Bioc   R BiocStatus RSPM MRAN
1 3.13 4.1       <NA> <NA> <NA>
```
