### ISSUE TITLE
Installing the GitHub package without asking for update

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/BiocManager#98]
Hi,

This looks quite surprising to me
```
> BiocManager::install("Bioconductor/AnVIL", update = FALSE, ask = FALSE)
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.12 (BiocManager 1.30.12), R 4.0.4 (2021-02-15)
Installing github package(s) 'Bioconductor/AnVIL'
Downloading GitHub repo Bioconductor/AnVIL@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: tibble (3.1.0 -> 3.1.1) [CRAN]
```
It turns out that the prompt is from `remotes::install_github` and I need to specify `upgrade = "never"` to silent it. It would be nice if this can be handled by `BiocManager::install` and `ask = FALSE` can work for the GitHub package as well.

Best,
Jiefei

**Comment by LiNk-NY** [comment]
Hi Jiefei, @Jiefei-Wang 
Can you try using the https://github.com/Bioconductor/BiocManager/tree/upgrade_github branch?

**Comment by LiNk-NY** [comment]
Hi JieFei, @Jiefei-Wang 
Can you create a new issue for this? 
Martin mentioned this during our meeting on Tuesday. 
Best,
Marcel
